# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ac3057fc358e533aa734a3af58d57ce5a62b5f9cc62e6e0ab9997244d11946de42db81954381739a32111239f88f929e386877aba8e54b3ea5bb4613130d241

test:
  secret_key_base: 6637ffd967400cb454e3aeac50b9676d7f89e05e8158d3d30e29676ff49aff2644fedece6926779d0a1591084399207d89c2fb295ee67c6586c1ebf3ef62bc17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
